### PR TITLE
chore: update dependencies for compatibility with PHP 8.3

### PR DESCRIPTION
**Pull request by ahonymous**
I hope this MR is based on the next version of the package.

### CODE REVIEW

**Comment by DavertMik** [comment]
Thank you

**Comment by ahonymous** [comment]
@DavertMik I fix a broken pipe in this PR. Please merge again.

**Comment by alaczi** [comment]
when we can expect this? Just wanted to try thestomatio but this blocks me.

**Comment by DavertMik** [comment]
Done! 
https://github.com/testomatio/php-list-tests/releases/tag/0.2.4

Thanks!

**Comment by alaczi** [comment]
@DavertMik thank you
Sadly, with this update now there is  another issue: https://github.com/testomatio/php-reporter/issues/5

**Pull request merged**
